### ISSUE TITLE
Differences between documentation and code: import_entities_from_graph

### ISSUE THREAD

**Issue by arcangelo7** [opencitations/oc_ocdm#4]
The documentation of the import_entities_from_graph method of the Reader class is out of date. In fact, the method takes three mandatory arguments, not two: the GraphSet, the Graph and the responsible agent. The latter is not mentioned in the documentation. Furthermore, import_entities_from_graph is also invoked by the sync_with_triplestore method of the graph_set module, but it is called without specifying the responsible agent, preventing its use.

**Comment by iosonopersia** [comment]
Hi @arcangelo7 !
Thank you very much for reporting this problem! I'm going to fix it in the following days. A new version of `oc_ocdm` will be published as a result.
Bye!

**Comment by iosonopersia** [comment]
Hi @arcangelo7 !
> Furthermore, import_entities_from_graph is also invoked by the sync_with_triplestore method of the graph_set module, but it is called without specifying the responsible agent, preventing its use.

This should be fixed in version 5.0.0 . Please, try to upgrade your local version by running the following command:
```bash
pip install -U oc_ocdm
```

As far as the documentation is concerned, I'm going to check it as soon as possible.
Bye!

**Comment by iosonopersia** [comment]
I checked the documentation right and it seems ok!

Perfect!

**Comment by arcangelo7** [comment]
I can confirm that it is perfect now, thank you!
