### ISSUE TITLE
Proposal to implement a helper method that returns AgentRoles in the correct order

### ISSUE THREAD

**Issue by arcangelo7** [opencitations/oc_ocdm#5]
I would like to make an implementation proposal. Currently, AgentRoles linked to a certain BibliographicResource via the pro:isDocumentContextFor predicate are not sorted, although the order was specified via the oco:hasNext predicate. This makes a lot of sense because if there is more than one type of AgentRole, such as the authors and the publisher, the order is no longer significant. However, the order of the AgentRoles is relevant and the user may want to get, for example, all the authors in the right order. At the moment, this operation must be done manually, using the oco:hasNext predicate. Therefore, it might be meaningful to implement a support method that allows performing this operation automatically, without the user having to do it every time.

**Comment by iosonopersia** [comment]
Hi @arcangelo7 !
This is actually a good suggestion. I'm already trying to figure out how to implement this functionality inside the library. I will update you as soon as I have found a solution.

Bye!

**Comment by iosonopersia** [comment]
Hi @arcangelo7 !
I've implemented the function that you requested!

Please upgrade to the latest version of oc_ocdm (5.0.0) by running the following command:
```bash
pip install -U oc_ocdm
```

Then, you can do like this:
```python
from rdflib import Namespace
from oc_ocdm.support import get_ordered_contributors_from_br

br = [...]

pro = Namespace("http://purl.org/spar/pro/")
ordered_authors = get_ordered_contributors_from_br(br, pro.author)
ordered_editors = get_ordered_contributors_from_br(br, pro.editor)
ordered_publishers = get_ordered_contributors_from_br(br, pro.publisher)
```

**Current implementation may contain bugs!** If you find something strange with this function, please report it here with another GitHub issue.

Bye!
